### ISSUE TITLE
Peer-review

### ISSUE THREAD

**Issue by hcwang24** [hcwang24/best_place_to_live#1]
## Mini - peer review activity
rubric={mechanics: 10}

Compare your Dash python dashboard with your milestone team members. If you completed this work in individually, your dashboard must be different from your other group team members.

[ ] - Write a short text explaining at least two pieces of constructive feedback for each team member and paste it as a github issue in their repositories. If you have 3 team members, you need to do it for their 3 apps. You will need to submit these links to Canvas.

### Name of the app: Van_houses
Link to the repo: https://github.com/hcwang24/best_place_to_live/tree/v0.0.1. 
Link to the _proposal.md_ file (where it is the description of the persona and scenario): https://github.com/hcwang24/best_place_to_live/blob/v0.0.1/reports/proposal.md

### Suggested topics for peer review:
Persona

Has the dashboard been created with the persona for whom it was designed in mind? Please, read the persona description in the proposal.md before anwsering this question

Has the dashboard been created with the usage scenario for which it was designed in mind? Please, read the usage scenario description in the proposal.md before anwsering this question

Suggest at least one more visualization you would include thinking on the persona and usage scenario

Frontend / layout
4. Is the text (plot labels / titles / subtitles / other text in the UI) easy to read? Do you understand the x and y axis legends in the plots?

Are the plots selected appropriated for the data? Could you think of other types of plots or improvements regarding interactivity/reactivity?

Was the dashboard organized in a way that was easy to read (columns / rows) or you would suggest a change in the dashboard layout organization?

Would you prefer to include tabs/navbars to improve the navigation or do you think it is better to visualize everything in one screen by the nature of the content? Why?

Are there labels for thhe widgets/Inputs? Do they make easier to understand the reactivity for the users?

Backend
9. Are all the options that you can select in the widgets working correctly? Have you found some options/combinations where you got errors?

Could be added reactive expressions to avoid code duplication?

Could be included dynamic UI elements or actions buttons? Or what other element - widget would you include?

Documentation.

Could you understand from the README.md how to use the app? Can the documentation be improved?

Was the app intuitive to use without reading the documentation? What information could be helpful to include?

Indicate some change (add or modify a visualization / change the design / include a reactive element) which you would like to include in your own app after reviewing this one

**Comment by mozhao0331** [comment]
Firstly, overall the app looks great! However, there are a few areas where improvements could be made.

-  The map is quite similar to the one in the group assignment; something new may be better. For example, you could add new elements or adjust the layout to make it more visually appealing or user-friendly. 

- The Pie chart is a little bit dense, it is quite hard to read if I select all the property types. One possible solution is to switch to other visualizations, such as a bar chart or a stacked bar chart, which may be easier to read and understand.

- You may consider adjusting the text size and the background, it is sometimes hard to read. Ensuring that the text is easily legible is critical for a user-friendly app, and adjusting the size and background can help improve readability.

Overall, the app looks great, and it's clear that a lot of effort has been put into its design. Nice work!

**Comment by zchen156** [comment]
Your dashboard is impressive and well-designed. Thank you for showing your efforts! The app provides valuable information with various selection options and corresponding interactive plots.

One suggestion I have is to simplify the background since the plots are information-intensive with colorful elements. The complex night city landscape could make it difficult to read the plots.

Additionally, I understand that the Vancouver housing dataset is extensive and it may take a long time to render the interactive plots. To improve the rendering time, you could consider taking samples from the original dataset for display purposes only.

Overall, your dashboard is fantastic, and I believe it will attract a lot of potential users.

**Comment by kenuiuc** [comment]
Very nice dashboard :100: 
- The option to switch between sampled and full size data is very handy. There's even a warning when you switch to full size :+1: 
- I feel like the map has too many small dots concentrated in a small area. My suggestion is to merge some small dots into bigger dots. Since the land price of nearby neighborhood tends to be very close. I think it's not necessary to show all the individual data points.
- The histogram by property type is not smooth enough. It might be a good idea to use density plot instead or increase the number of buckets.
- I love the design for the drop down checklist.
